### ISSUE TITLE
Getting error on adding refreshtoken.

### ISSUE THREAD

**Issue by NajibbUllah** [kodlamaio-projects/nArchitecture.RentACarProject#105]
Hi!

I run the code first migration. Registered a user successfully. But right after the registration of user, these is a line **"RefreshToken addedRefreshToken = await _authService.AddRefreshToken(createdRefreshToken);"**  in the **Handle()** method of **RegisterCommand**. On Execting that line I am getting the following error
**"Non-exhaustive switch expression failed to match its input.
Unmatched value was Unchanged."**

Do you have any idea why I am getting this error on adding refresh token?

**Comment by uluserdar** [comment]
This bug has been fixed. Awaiting approval for the fix.

Related fix
#97

**Comment by ahmet-cetinkaya** [comment]
Also, awaiting a response from the developer. #73

**Comment by uluserdar** [comment]
This issue can be closed. #79 has been merged. This fixes the problem and looks good
