### ISSUE TITLE
Silme, Güncelleme işlem hatası

### ISSUE THREAD

**Issue by alisari41** [kodlamaio-projects/nArchitecture.RentACarProject#118]
Merhabalar, 
[nArchitecture.RentACarProject](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject)/[src](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src)/[rentACar](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar)/[Application](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar/Application)/[Features](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar/Application/Features)/[Brands](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar/Application/Features/Brands)/[Commands](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar/Application/Features/Brands/Commands)/[DeleteBrand](https://github.com/kodlamaio-projects/nArchitecture.RentACarProject/tree/master/src/rentACar/Application/Features/Brands/Commands/DeleteBrand)/DeleteBrandCommand.cs sınıfı içerisinde Handle(...) Metodunda **await _brandBusinessRules.BrandIdShouldExistWhenSelected(request.Id);** satırında verinin varlığını kontrol ettikten sonra silme işlemini gerçekleştiremiyor. Hata mesajı almıyorum fakat veri tabanında silmek istenen veri duruyor. Eğer  belirtilen satır açıklama satırına alınırsa (veri varlığı sorgulanmazsa) silme işlemi bu sefer doğru bir şekilde gerçekleşiyor. Acaba repository yi dispose etmediğimizden olabilir mi? 

Şu şekilde bir tablomuz olduğunu varsayalım. Eğer tablomuzda sadece id numarası 1 olan bir verimiz olduğunu varsayarsak ve belirtilen sorgudaki kodu değiştirirsek. Mesela  `_ProgrammingLanguage? result = await _programmingLanguageRepository.GetAsync(b => b.Id != id);
            if (result != null) throw new BusinessException("........");` bu işlemde 1 numaralı id silinmek istediğinde silme işlemi gerçekleştirecektir. Fakat birden fazla verimiz olduğunda ve ilk verilerden birini seçtiğimizde bu sorgu yanlış olacaktır onu anladım fakat bu sorguyu yazmamım asıl amacı hata nedenin yazarak anlatabilmek. 

Kısacası benim anladığım biz verinin varlığını sorgulamaya çalıştığımızda repository.GetAsync() işleminde eğer veriyi bulursa örneğin 1 id li veriyi buldu  ve bu veri var olduğu için hata mesajı fırlatmayacağından dolayı bu veriyi silemiyoruz. Silme işleminde bir hata ile karşılaşılmamıştır fakat silme gerçekleşmemektedir..

Veri  Kontrollü Silme İşlemi 
![Sorgu dahilinde silme işlemi](https://user-images.githubusercontent.com/81421228/206862536-c801c476-09f7-4798-8f3d-6adc0946181d.PNG)

Veri Kontrolsüz Silme İşlemi
![image](https://user-images.githubusercontent.com/81421228/206862548-fca7c9d6-06de-4970-99b0-2ad5d8b23ebc.png)

Kodlama.io ödevi üzerinden fotoğraf gösterebildim. Projeyi redis hatası yüzünden açamadım. Bu sebepten dolayı kodları kontrol ederekten diğer proje üzerinden fotoğraf ekledim.

**Comment by sugrado** [comment]
Merhaba, Automapper ile parametre olarak gönderilen id maplenerek bir Brand nesnesi oluşturulmuş. Fakat oluşan bu Brand EntityFramework tarafından takip edilmediği için veritabanında herhangi bir silme işlemi gerçekleşmiyor. Bu sorunu çözmek için silme işlemini metnin sonundaki kod parçacığı ile gerçekleştirebilirsiniz. Alternatif bir çözüm için ise Persistence'da bir method yazarak `DbSet<TEntity>.Attach(TEntity entity)` ile Brand'in EntityFramework tarafından tanınmasını sağlayabilirsiniz.
İyi çalışmalar.

``` cs
var brand = await _brandRepository.GetAsync(p => p.Id == request.Id);
_brandBusinessRules.BrandShouldExistWhenRequested(brand);
var deletedBrand = await _brandRepository.DeleteAsync(brand);
return _mapper.Map<DeletedBrandDto>(deletedBrand);
```

**Comment by alisari41** [comment]
Yardımın için çok teşekkür ederim. İlk attığın çözüm ile silme işlemini gerçekleştirebildim. Fakat ikinci gösterdiğin alternatif çözümü yaparken `System.InvalidOperationException: The instance of entity type 'Programming Language' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.` bu şekilde bir hata aldım. Eğer vaktin varsa bu iki çözüm arasındaki fark bizi ilerde etkiler mi öğrenebilir miyim?

**Comment by alisari41** [comment]
Görkem (@sugrado), Yardımın için çok teşekkür ederim. İlk attığın çözüm ile silme işlemini gerçekleştirebildim. Fakat ikinci gösterdiğin alternatif çözümü yaparken ` System.InvalidOperationException: The instance of entity type 'Programming Language' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.` bu şekilde bir hata aldım. Eğer vaktin varsa bu iki çözüm arasındaki fark bizi ilerde etkiler mi öğrenebilir miyim?

**Comment by alisari41** [comment]
> Görkem (@sugrado), Yardımın için çok teşekkür ederim. İlk atılan çözüm dosyası silme işlemini gerçekleştirebildim. Ancak ikinci sergilenen alternatif çözümü yaparken ` System.InvalidOperationException: The instance of entity type 'Programming Language' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.`bu şekilde bir hata aldım. Eğer vaktin varsa bu iki çözüm arasındaki fark bizi ilerde etkiler mi öğrenebilir miyim?

@sugrado Tekrardan Merhaba,
Silme işleminde birinci yöntem belirttiğim gibi sağlıklı bir şekilde çalıştı fakat güncelleme işleminde bu işleminde mecbur bir şekilde mapleme yapmak zorunda kalıyorum ve ikinci yöntemi yapamadığım için mapleme yapamıyorum. Mapleme işlemi yapmak için zorunda kalmamım sebebi mesela 27 numaralı id güncelleme yapmadan önce sorguda bakıyorum ve bu tabloda olduğunu varsayım. Ben 27 numaralı id'i "x" yapmak istiyorum ama bana sorgudan "tabldaki değeri getiriyor" bu sebepten dolayı ...Command request ile mapleme yaparaktan işlem yapmam gerekir (yoksa girilen veriyi güncellemiyor). Şu anlık manuel olarak dönen değer.Name=request.Name şeklinde verdim. İlerde büyük tablolarda böyle bir sıkıntıda mapleme yapmadan manuel vermek biraz sıkıntı çıkarır gibime geldi. Yardım edebilirsen sevinirim.

**Comment by sugrado** [comment]
Merhaba, ilk mesajınızdaki hata için muhtemelen EntityFramework tarafından daha önceden takipte olan bir nesneyi tekrar Attach ile takip etmek istemişsiniz. Attach kullanımına dikkat etmek gerekiyor.

İkinci mesajınız için ise sanırım ilk attığım mesajda beni yanlış anladınız. Mapleme yapmak için bir sınırınız yok. `değer.Name=request.Name` yöntemi dediğiniz gibi uzun vadede büyük tablolarda kalabalık yapacaktır fakat kullanımında bir sakınca yok tamamen tercih meselesi. Mapper ile güncelleme işlemi için ise [bağlantıdaki](https://github.com/sugrado/Kodlama.io.Devs/blob/master/src/kodlamaIoDevs/Application/Features/OperationClaims/Commands/UpdateOperationClaim/UpdateOperationClaimCommand.cs#L32) örneği inceleyebilirsiniz.

**Comment by alisari41** [comment]
Görkem (@sugrado) yardımın için teşekkür ederim.
