### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by kleenkanteen** [kodlamaio-projects/nArchitecture.RentACarProject#80]
Why was this project started? What is this supposed to do? Readme is empty. Found this place with the githunt extension and have no idea why it has so many stars.

**Comment by ahmet-cetinkaya** [comment]
> As Kodlama.io, we decided to share examples of completed projects. Inspired by Clean Architecture, nArchitecture is a monolith project. In this project, which is a rental car simulation, we have completed the project with advanced techniques. A project has been created that includes Clean Architecture, CQRS, Advanced Repository, Dynamic Querying, JWT, OTP, Google & Microsoft Auth, Role Based Management, Distributed Caching(Redis), Logging (Serilog), Elastic Search, and much more.

**Comment by kleenkanteen** [comment]
Kodlama.io link is broken btw.

**Comment by kleenkanteen** [comment]
Clicking on your link made it work. But typing it in the url multiple times
and copy pasting that URL did not work. Odd.
